services:
  web:
    env_file:
      - .env
    restart: always
    image: lcbruit/image_study_merge_web:latest
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:8000"
    volumes:
      - "${DATA_DIRECTORY}:/uploads"
  worker:
    env_file:
      - .env
    restart: always
    image: lcbruit/image_study_merge_celery:latest
    command: worker
    volumes:
      - "${DATA_DIRECTORY}:/uploads"
